services:
  casa-da-mae-postgres-db:
    image: bitnami/postgresql:latest
    container_name: casa-da-mae-postgres-db
    ports:
      - "5433:5432"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER:-docker}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-docker}
      - POSTGRES_DB=casa-da-mae
    volumes:
      - db_volume:/bitnami/postgresql
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - casa-da-mae-postgres-db
    networks:
      - local-network

volumes:
  db_volume:

networks:
  local-network:
    driver: bridge